swagger: '2.0'
info:
    version: "1.0.0"
    title: DASPANEL System API
    description: |

        System related API methods.

        The first version of the Daspanel Sites API is an exciting step forward 
        towards making an hosting control panel using Docker. We created it so 
        that you can create any site, plain or using PHP, in your local machine 
        and when ready easy deploy it on an public server exactly as you see it 
        in the development machine.

        Build something great!

    version: "1.0"
    termsOfService: http://daspanel.com/terms/
    contact:
        name: Daspanel API team
        email: admin@daspanel.com
        url: http://daspanel.com
    license:
        name: GPL-3
        url: https://opensource.org/licenses/GPL-3.0
# array of all schemes that your API supports
schemes:
    - http
    - https
consumes:
    - application/json
produces:
    - application/json
paths:
  /status:
    get:
      tags: [API Server]
      operationId: modules.base.api.status
      summary: Get api server status
      responses:
        200:
          description: Api without issues
        404:
          description: Api with issues
  /services:
    get:
      tags: [API Server]
      operationId: modules.base.api.services
      summary: Get services endpoints in API server
      responses:
        200:
          description: Return services list endpoint
          schema:
            type: array
            items:
              $ref: '#/definitions/Services'

definitions:
  Services:
    type: object
    properties:
      service:
        type: string
        description: Service name
        example: "databases"
        readOnly: true
      urls:
        type: object
        description: Url's endpoint's
        properties:
          endpoint:
            type: string
            description: Endpoint address
            example: "/1.0/databases"
            readOnly: true
          endpoint_doc:
            type: string
            description: Endpoint API doc
            example: "/1.0/databases/ui"
            minLength: 1

